version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - "9080:9000"
    environment:
      - SERVICES=http://myapp:8080,http://myapp:8080  
    volumes:
      - ./proxy:/usr/src/proxy

  myapp:
    build: .
    environment: 
      - DATABASE_URL=postgres://postgres@mydb:5432/postgres
    volumes:
      - .:/usr/src/app
    depends_on:
      - mydb
  
  myapp2:
    build: .
    environment: 
      - DATABASE_URL=postgres://postgres@mydb:5432/postgres
    volumes:
      - .:/usr/src/app
    depends_on:
      - mydb
  
  mydb:
    image: postgres:alpine
    volumes:
      - psql-db:/var/lib/psql/data  

volumes:
  psql-db : 
      driver_opts: 
        type: none 
        device: /Users/pragyar/classroom/dockerSession/composeAsgnmnt
        o: bind 